title: Raymond Morland's Website
email: raymondmorland@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Raymond Morland
baseurl: ""
url: "https://raymorland.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
theme: null
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

include: [_pages]

sass:
  style: compressed
